# version: 6

# Use Ubuntu Trusty 14.04 image; unfortunately, it requires "sudo: true"
# and thus is very slow :(
dist: trusty
sudo: true

language: scala
scala:
  - 2.12.4

cache:
  directories:
    - $HOME/.ivy2

env:
  global:
    - KAITAI_STRUCT_VERSION=0.9-SNAPSHOT${TRAVIS_BUILD_ID}

addons:
  apt:
    packages:
      # Debian package build
      - dpkg
      - dpkg-sig
      - dpkg-dev
      - lintian
      - fakeroot

script:
  - cd tests
  - ./build-compiler
  - cd ../compiler
  - sbt compilerJVM/debian:packageBin
  - ./publish_deb_to_bintray.sh && ../trigger-kaitai_struct_python_docker
  - sbt compilerJVM/universal:packageBin
  - ./publish_zip_to_bintray.sh
  - cd ../tests
  - ./publish-js-compiler
  - ./translator-tests || true
  - ./build-formats
  - ./publish-targets

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c6bd60df4d171f9d3789
